# Generated by Django 5.0 on 2023-12-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('agree', models.BooleanField()),
                ('date', models.DateField()),
                ('birth_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('url_field', models.URLField()),
            ],
        ),
    ]
